# Site settings
title: "技术积累"
author: "LinuxparaChen"
description: "这是一个私人博客，记录平时的一些技术积累。"
keywords: "C, C++, Android, OpenCV, OpenGL-ES"
#biography: "I am a Professor of Software Engineering at the <a href='http://www.fe.up.pt'>Faculty of Engineering</a>, University of Porto and Senior Researcher at <a href='https://www.inesctec.pt'>INESC TEC</a>. Here you can find my <a href='/assets/thesis.pdf'>PhD Thesis</a> and my <a href='/assets/cv.pdf'>Résumé</a>."
colophon: "© 主题借鉴Papyrus 原著作者：Hugo Sereno Ferreira. <a href='https://github.com/mattvh/jekyllthemes'>原著主题.</a><br>Modify by LinuxparaChen.<br>"

baseurl: ""
url: "http://LinuxparaChen.github.io"

#twitter_username: ferreira_hugo
email: 13073134757@163.com
github_username: LinuxparaChen
#linkedin_username: hugoserenoferreira
#facebook_username: hugo.sereno.ferreira
#google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
